# -*- coding: utf-8 -*-
"""Class_Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbhtdcbqZkfT8kYirS7__fOrkHW6ZPZI
"""

print('Hello World')

myname = "Sanchaita"
print(myname)

# x=4
# y=1
x = input("Enter any number ");
y = input("Enter any number ");
z= int(x) + int(y)
print("User enter number", z)
# z=x+y
# sum=z
# print(sum)
# print ("Addtion is",x,"and",y,"is=",sum)

# print(type(sum))

x=4
y=1
z=x-y
sub=z
print(sub)

x=4
y=5
z=x*y
multipay=z
print(multipay)

x=20
y=2
z=x/y
div=z
print(div)

x='5'
y=6
z=int(x)+y
sum=z
print("this is add",sum)

# myFname="Sanchaita "
ques= "what is your name?"
# myLname= "Biswas"
# fullname=myFname + myLname
# print("this is add two string",fullname)
print(ques + "=Sanchaita Biswas")
print(type(ques))

#print is patten A

print("    *")
print("  *   *")
print("  *****")
print(" *      *")
print(" *      *")
print()

nameUser =input("Welcome to  python class ");
print("Enter your name ",nameUser)

userName = input("Enter your name: ")
subone = input("plases enter your Math marks : ")
subtwo = input("plases enter your Phy marks :")
subthree = input("plases enter Bio your marks :")
subfour = input("plases enter Com your marks :")
subfive = input("plases enter Cem your marks :")

total = int(subone) + int(subtwo) + int(subthree) + int(subfour) + int(subfive)
average = total/5
print('Show of total marks: ' ,total)
print('Show of average of total mark: ', average)

"1234556".isdigit()

"sname".upper()

"CAN".lower()

str = "this";  # No space & digit in this string
str2 = "this is string example....wow!!!"
print (str.isalpha())
print (str2.isalpha())

str = "this2016" 
str2 = "this is string example....wow!!!" 
print (str.isalnum())
print (str2.isalpha())

# name="Tia","Pia","Tina","Hina","Bella"
# nametwo="Pia"
# print(nametwo in name)
name= input("Enter the same name : ")
nametwo=input("Check the name: ")
print(nametwo in name)
# print(type(name))

name="Tia","Pia","Tina","Hina","Bella"
name_ask = input("enter an item to check if it is on the name: ")
new_name= name
print(name_ask, 'on the new name is',menu_ask.lower() in new_name.lower())
print(new_name)

menu = "salad, pasta, sandwich, pizza, drinks, dessert"
# --Completed--
menu = "salad, pasta, sandwich, pizza, drinks, dessert"
print('pizza in menu = ','pizza' in menu)

menu = "salad, pasta, sandwich, pizza, drinks, dessert"
menu = "salad, pasta, sandwich, pizza, drinks, dessert"
print('pizza in menu = ','pizza' in menu)
print('soup in menu = ', 'soup' in menu)
print('dessert in menu = ', 'dessert' in menu)
menu_ask = input("enter an item to check if it is on the menu: ")
new_menu= menu_ask
print(menu_ask, 'on the new menu is',menu_ask.lower() in new_menu.lower())

def my_function():
  print("Hello from a function")

my_function()

def add_num(a,b):
    sum=a+b;
    return sum; 

num1=25  
num2=55
print("The sum is",add_num(num1,num2))